name: Scheduled Model Retraining

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  
  workflow_dispatch:

jobs:

  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Retrain the model
      run: |
        python model/train_model.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add model/stock_model.pkl model/scaler.pkl
        git diff --staged --quiet || git commit -m "feat(bot): Retrain model and update artifacts"
        git push origin HEAD:main